export const FETCH_ENTITY = 'ENTITY__FETCH_ENTITY';
export const FETCH_ENTITY_SUCCESS = 'ENTITY__FETCH_ENTITY_SUCCESS';
export const FETCH_ENTITY_ERROR = 'ENTITY__FETCH_ENTITY_ERROR';

export const UPDATE_ENTITY = 'ENTITY__UPDATE_ENTITY';
export const UPDATE_ENTITY_SUCCESS = 'ENTITY__UPDATE_ENTITY_SUCCESS';
export const UPDATE_ENTITY_ERROR = 'ENTITY__UPDATE_ENTITY_ERROR';

export const CREATE_ENTITY = 'ENTITY__CREATE_ENTITY';
export const CREATE_ENTITY_SUCCESS = 'ENTITY__CREATE_ENTITY_SUCCESS';
export const CREATE_ENTITY_ERROR = 'ENTITY__CREATE_ENTITY_ERROR';

export const DELETE_ENTITY = 'ENTITY__DELETE_ENTITY';
export const DELETE_ENTITY_SUCCESS = 'ENTITY__DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_ERROR = 'ENTITY__DELETE_ENTITY_ERROR';
