export const FETCH_ENTITY_LIST = 'ENTITY_LIST__FETCH_ENTITY_LIST';
export const FETCH_ENTITY_LIST_SUCCESS = 'ENTITY_LIST__FETCH_ENTITY_LIST_SUCCESS';
export const FETCH_ENTITY_LIST_ERROR = 'ENTITY_LIST__FETCH_ENTITY_LIST_ERROR';
